/**
 * MergeQueue — Cycle 4 / T4.4
 *
 * Subscribes to `agent.branch.pushed` events emitted by Workstream CC
 * (agent-commit.ts), opens a draft GitHub PR per agent branch, and maintains
 * an append-only ledger at:
 *
 *   .agentforge/cycles/<cycleId>/agent-prs.json
 *
 * Ledger schema (one object per element in the top-level array):
 * {
 *   prNumber:  number | null,
 *   prUrl:     string | null,
 *   branch:    string,
 *   agentId:   string,
 *   cycleId:   string,
 *   itemIds:   string[],
 *   status:    'open' | 'dry-run' | 'skipped-no-gh',
 *   openedAt:  string  (ISO 8601)
 * }
 *
 * Atomic writes: write to <file>.tmp then rename over the real path so
 * concurrent readers never see a partial JSON file.
 */

import { execFile as execFileCb } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { promisify } from 'node:util';
import type { MessageBusV2 } from '../message-bus/message-bus.js';
import type { AgentBranchPushedPayload, MergeQueuePrOpenedPayload } from '../message-bus/types.js';
import type { MessageEnvelopeV2 } from '../message-bus/types.js';

const execFile = promisify(execFileCb);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface MergeQueueOptions {
  projectRoot: string;
  bus: MessageBusV2;
  /** Target branch for draft PRs. Defaults to reading cycle.json, then 'main'. */
  parentBranch?: string;
  /** When true, never call gh; record entries with status='dry-run'. */
  dryRun?: boolean;
}

export interface AgentBranchPushedEvent extends AgentBranchPushedPayload {
  topic: 'agent.branch.pushed';
}

export interface LedgerEntry {
  prNumber: number | null;
  prUrl: string | null;
  branch: string;
  agentId: string;
  cycleId: string;
  itemIds: string[];
  status: 'open' | 'dry-run' | 'skipped-no-gh';
  openedAt: string;
}

export interface DrainResult {
  pushed: number;
  prs: Array<{ prNumber: number; branch: string; agentId: string }>;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readLedger(ledgerPath: string): LedgerEntry[] {
  if (!existsSync(ledgerPath)) return [];
  try {
    const raw = readFileSync(ledgerPath, 'utf-8').trim();
    if (!raw) return [];
    return JSON.parse(raw) as LedgerEntry[];
  } catch {
    return [];
  }
}

function writeLedger(ledgerPath: string, entries: LedgerEntry[]): void {
  const tmpPath = ledgerPath + '.tmp';
  writeFileSync(tmpPath, JSON.stringify(entries, null, 2) + '\n', 'utf-8');
  renameSync(tmpPath, ledgerPath);
}

function appendToLedger(ledgerPath: string, entry: LedgerEntry): void {
  const dir = ledgerPath.substring(0, ledgerPath.lastIndexOf('/'));
  mkdirSync(dir, { recursive: true });
  const entries = readLedger(ledgerPath);
  entries.push(entry);
  writeLedger(ledgerPath, entries);
}

function resolveCycleDir(projectRoot: string, cycleId: string): string {
  return join(projectRoot, '.agentforge', 'cycles', cycleId);
}

function resolveParentBranchFromCycleJson(
  projectRoot: string,
  cycleId: string,
): string | null {
  const cycleJsonPath = join(resolveCycleDir(projectRoot, cycleId), 'cycle.json');
  if (!existsSync(cycleJsonPath)) return null;
  try {
    const json = JSON.parse(readFileSync(cycleJsonPath, 'utf-8')) as Record<string, unknown>;
    // cycle.json stores the autonomous branch under git.branch
    const gitBranch = (json['git'] as Record<string, unknown> | undefined)?.['branch'];
    if (typeof gitBranch === 'string' && gitBranch) return gitBranch;
  } catch {
    // ignore
  }
  return null;
}

async function openDraftPr(opts: {
  parentBranch: string;
  branch: string;
  agentId: string;
  itemIds: string[];
  diffSummary: string;
  cycleId: string;
  projectRoot: string;
}): Promise<{ prNumber: number; prUrl: string }> {
  const title = `agent(${opts.agentId}): ${opts.itemIds.join(', ')}`;
  const body = [
    `## Agent PR — ${opts.agentId}`,
    '',
    `**Cycle:** ${opts.cycleId}`,
    `**Branch:** \`${opts.branch}\``,
    `**Base:** \`${opts.parentBranch}\``,
    `**Items:** ${opts.itemIds.join(', ')}`,
    '',
    '### Diff summary',
    '```',
    opts.diffSummary.slice(0, 2000),
    '```',
    '',
    '_Auto-generated by MergeQueue (T4.4)_',
  ].join('\n');

  const { stdout } = await execFile(
    'gh',
    [
      'pr',
      'create',
      '--draft',
      '--base',
      opts.parentBranch,
      '--head',
      opts.branch,
      '--title',
      title,
      '--body',
      body,
    ],
    { cwd: opts.projectRoot },
  );

  // `gh pr create` prints the PR URL on the last non-empty line
  const lines = stdout.trim().split('\n').filter(Boolean);
  const prUrl = lines[lines.length - 1] ?? '';

  // Extract number from URL like https://github.com/owner/repo/pull/42
  const match = prUrl.match(/\/pull\/(\d+)$/);
  const prNumber = match ? parseInt(match[1]!, 10) : NaN;

  if (isNaN(prNumber) || prNumber === 0) {
    throw new Error(`gh pr create returned an unexpected URL: ${prUrl}`);
  }

  return { prNumber, prUrl };
}

// ---------------------------------------------------------------------------
// MergeQueue
// ---------------------------------------------------------------------------

export class MergeQueue {
  private readonly projectRoot: string;
  private readonly bus: MessageBusV2;
  private readonly parentBranchOverride: string | undefined;
  private readonly dryRun: boolean;

  private unsubscribe: (() => void) | null = null;
  /** Tracks in-flight handler promises so drain() can await them. */
  private readonly inFlight = new Set<Promise<void>>();

  constructor(opts: MergeQueueOptions) {
    this.projectRoot = opts.projectRoot;
    this.bus = opts.bus;
    this.parentBranchOverride = opts.parentBranch;
    this.dryRun = opts.dryRun ?? false;
  }

  /** Subscribe to agent.branch.pushed topic and begin processing. */
  start(): void {
    if (this.unsubscribe) return; // already started
    this.unsubscribe = this.bus.subscribe<AgentBranchPushedPayload>(
      'agent.branch.pushed',
      (envelope: MessageEnvelopeV2<AgentBranchPushedPayload>) => {
        const p = this.handleEvent(envelope.payload).catch((err) => {
          console.error('[MergeQueue] Unhandled error in handler:', err);
        });
        this.inFlight.add(p);
        void p.finally(() => {
          this.inFlight.delete(p);
        });
      },
    );
  }

  /** Unsubscribe from the bus — new events will be ignored. */
  stop(): void {
    if (this.unsubscribe) {
      this.unsubscribe();
      this.unsubscribe = null;
    }
  }

  /**
   * Wait for all in-flight event handlers to complete.
   * Returns a summary of pushed branches and opened PRs from the ledger.
   */
  async drain(): Promise<DrainResult> {
    if (this.inFlight.size > 0) {
      await Promise.allSettled([...this.inFlight]);
    }

    // Aggregate from all cycle ledgers we may have written
    const cyclesDir = join(this.projectRoot, '.agentforge', 'cycles');
    const prs: Array<{ prNumber: number; branch: string; agentId: string }> = [];
    let pushed = 0;

    if (existsSync(cyclesDir)) {
      const { readdirSync } = await import('node:fs');
      for (const cycleId of readdirSync(cyclesDir)) {
        const ledgerPath = join(cyclesDir, cycleId, 'agent-prs.json');
        const entries = readLedger(ledgerPath);
        pushed += entries.length;
        for (const e of entries) {
          if (e.status === 'open' && e.prNumber != null) {
            prs.push({ prNumber: e.prNumber, branch: e.branch, agentId: e.agentId });
          }
        }
      }
    }

    return { pushed, prs };
  }

  // ── Private ────────────────────────────────────────────────────────────────

  private async handleEvent(payload: AgentBranchPushedPayload): Promise<void> {
    const { cycleId, agentId, branch, baseBranch, itemIds, diffSummary, pushedAt, localOnly } =
      payload;

    // Skip entirely when local-only (no remote)
    if (localOnly === true) {
      console.log(`[MergeQueue] Skipping ${branch} (localOnly=true)`);
      return;
    }

    const ledgerPath = join(resolveCycleDir(this.projectRoot, cycleId), 'agent-prs.json');

    // Determine parent branch: override > cycle.json > baseBranch > 'main'
    const parentBranch =
      this.parentBranchOverride ??
      resolveCycleFromCycleJson(this.projectRoot, cycleId) ??
      baseBranch ??
      'main';

    if (this.dryRun) {
      const entry: LedgerEntry = {
        prNumber: null,
        prUrl: null,
        branch,
        agentId,
        cycleId,
        itemIds,
        status: 'dry-run',
        openedAt: new Date().toISOString(),
      };
      appendToLedger(ledgerPath, entry);

      this.bus.publish<MergeQueuePrOpenedPayload>({
        from: 'system',
        to: 'broadcast',
        topic: 'merge-queue.pr.opened',
        category: 'system',
        payload: {
          cycleId,
          agentId,
          branch,
          prNumber: null,
          status: 'dry-run',
          prUrl: null,
          openedAt: entry.openedAt,
        },
      });

      console.log(`[MergeQueue] dry-run — recorded ${branch} (no gh call)`);
      return;
    }

    // Live mode: attempt to open a draft PR
    let entry: LedgerEntry;
    try {
      const { prNumber, prUrl } = await openDraftPr({
        parentBranch,
        branch,
        agentId,
        itemIds,
        diffSummary,
        cycleId,
        projectRoot: this.projectRoot,
      });

      entry = {
        prNumber,
        prUrl,
        branch,
        agentId,
        cycleId,
        itemIds,
        status: 'open',
        openedAt: pushedAt,
      };

      console.log(`[MergeQueue] Opened draft PR #${prNumber} for ${branch}: ${prUrl}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`[MergeQueue] gh pr create failed (${msg}); recording as skipped-no-gh`);

      entry = {
        prNumber: null,
        prUrl: null,
        branch,
        agentId,
        cycleId,
        itemIds,
        status: 'skipped-no-gh',
        openedAt: pushedAt,
      };
    }

    appendToLedger(ledgerPath, entry);

    this.bus.publish<MergeQueuePrOpenedPayload>({
      from: 'system',
      to: 'broadcast',
      topic: 'merge-queue.pr.opened',
      category: 'system',
      payload: {
        cycleId,
        agentId,
        branch,
        prNumber: entry.prNumber,
        status: entry.status,
        prUrl: entry.prUrl,
        openedAt: entry.openedAt,
      },
    });
  }
}

/** Read the cycle's autonomous branch from cycle.json. */
function resolveCycleFromCycleJson(projectRoot: string, cycleId: string): string | null {
  return resolveParentBranchFromCycleJson(projectRoot, cycleId);
}
