// packages/core/src/autonomous/pr-body-renderer.ts
import type { CycleResult, TestResult, ScoringResult } from './types.js';

export interface PrBodyInput {
  sprint: {
    version: string;
    items: Array<{ id: string; priority: string; title: string; assignee: string }>;
  };
  result: CycleResult;
  testResult: TestResult;
  scoringResult: ScoringResult;
}

export function renderPrBody(input: PrBodyInput): string {
  const { sprint, result, testResult, scoringResult } = input;

  const itemsList = sprint.items
    .map(i => `- **${i.priority}** ${i.title} — \`${i.assignee}\``)
    .join('\n');

  const filesList = result.git.filesChanged.length > 0
    ? result.git.filesChanged.map(f => `- \`${f}\``).join('\n')
    : '_(none)_';

  const costBreakdown = Object.entries(result.cost.byAgent)
    .sort(([, a], [, b]) => b - a)
    .map(([agent, cost]) => `- \`${agent}\`: $${cost.toFixed(2)}`)
    .join('\n');

  const passRatePct = (testResult.passRate * 100).toFixed(1);
  const durationMin = (result.durationMs / 60000).toFixed(1);

  return `## Autonomous Cycle: v${sprint.version}

**Cycle ID:** \`${result.cycleId}\`
**Duration:** ${durationMin} minutes
**Cost:** $${result.cost.totalUsd.toFixed(2)} / $${result.cost.budgetUsd.toFixed(2)}
**Stage:** \`${result.stage}\`

### Sprint items
${itemsList}

### Test results
- ${testResult.passed} passed
- ${testResult.failed} failed
- ${testResult.skipped} skipped
- **Pass rate:** ${passRatePct}%

### Scoring rationale
${scoringResult.summary}

### Files changed
${filesList}

### Cost breakdown (by agent)
${costBreakdown}

---

Generated by AgentForge autonomous loop.
Cycle logs: \`.agentforge/cycles/${result.cycleId}/\`

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>
`;
}
